### ISSUE TITLE
Verified smart contracts

### ISSUE THREAD

**Issue by pieterhartel** [SmaCo/UnicoToken#1]
You mentioned that your UnicoToken contract has been verified. May I ask what motivated you to have your contract etherscan.io? I am interested in the reasons people have to verify their contracts. For example:

1) Did you expect that verification would generate more interest in your contract?
2) Have you experienced more success in your business because of the verification?
3) Were there any down sides to the verification? E.g. making the source public...
4) How did you find out about the possibility to have your contract verified?
5) Why do you think that there is only one site that offers this service?
6) Were you satisfied with the services offered by etherscan.io?
7) How many smart contracts did you have verified (including this one)?
8) Will you continue to have smart contracts verified? 
9) Would you recommend others to have their contracts verified?
10) Do you think that smart contracts that are verified are also better contracts?

Thank you very much for your time to drop me a quick reply.

I am a university researcher interested in block chain security.
I have no connection to etherscan.io.

—pieter, https://www.tudelft.nl/staff/pieter.hartel/

**Comment by cryptovale-eth** [comment]
I privately answered Pieter, apologizing for having not seen this in the last years, as this account has been inactive since then...
